# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_remove_user_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='poke',
            field=models.ManyToManyField(related_name='_user_poke_+', to='login_app.User'),
        ),
    ]
