# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_auto_20170108_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='poke',
            field=models.ManyToManyField(related_name='poke_to', to='login_app.User'),
        ),
    ]
